from .BasReliefPanel import *
from .ButtonsPanel import *
from .ChainsPanel import *
from .InfoPanel import *
from .MachinePanel import *
from .OperationsPanel import *
from .PackPanel import *
from .CurveCreatorPanel import *
from .SlicePanel import *
from .CustomPanel import *
from .CurveToolsPanel import *