from .BASRELIEF_Panel import *
from .CAMButtonsPanel import *
from .CAMChainsPanel import *
from .CAMInfoPanel import *
from .CAMMachinePanel import *
from .CAMOperationsPanel import *
from .CAMPackPanel import *
from .CAMPTToolsCreate import *
from .CAMSlicePanel import *
from .CustomPanel import *
from .VIEW3D_PT_tools_curvetools import *